ticketing:
    entities:
        ticket:               'App\Entity\Ticket'
        ticket_category:      'App\Entity\TicketCategory'
        ticket_comment:       'App\Entity\TicketComment'
        ticket_history:       'App\Entity\TicketHistory'
        ticket_keyword:       'App\Entity\Ticket\Keyword'
        ticket_status:        'App\Entity\TicketStatus'
    templates:
        layout: 'base.html.twig'
    assets:
        stylesheets:
            - bundles/ticketing/vendor/css/bootstrap.min.css
            - bundles/ticketing/vendor/css/bootstrap-datepicker3.min.css
            - bundles/ticketing/vendor/css/font-awesome.min.css
            - bundles/ticketing/vendor/css/select2.min.css
            - bundles/ticketing/vendor/css/ionicons.min.css
            - bundles/ticketing/vendor/css/dataTables.min.css
            - bundles/ticketing/css/AdminLTE.min.css
            - bundles/ticketing/css/skin-ticketing.min.css
            - bundles/ticketing/css/helper.css
        javascripts:
            - bundles/ticketing/vendor/js/jquery.min.js
            - bundles/ticketing/vendor/js/bootstrap.min.js
            - bundles/ticketing/vendor/js/adminlte.min.js
            - bundles/ticketing/vendor/js/bootstrap-datepicker.min.js
            - bundles/ticketing/vendor/js/bootstrap-datepicker.fr.min.js
            - bundles/ticketing/vendor/js/select2.min.js
            - bundles/ticketing/vendor/js/select2-fr.min.js
            - bundles/ticketing/vendor/js/dataTables.min.js
            - bundles/ticketing/js/script.js

