#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ticketing_routing:
  resource: '@TicketingBundle/Resources/config/routing/routes.yaml'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
